name: Build APK CryptoGuard

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Liberar Espaço e Limpar Caches
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY"
          rm -rf ~/.gradle
          rm -rf ~/.buildozer

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Dependências do Sistema
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake git python3-dev python3-pip \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            zlib1g-dev pkg-config libffi-dev libssl-dev autoconf automake \
            libtool unzip zip libsqlite3-dev

      - name: Instalar Buildozer
        run: pip3 install --user --upgrade pip "cython<3.0" "setuptools<70.0.0" buildozer

      - name: Compilar APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          
          # Localiza o sdkmanager dinamicamente no Runner
          SDK_PATH=$(find $ANDROID_HOME -name "sdkmanager" | grep "bin/sdkmanager" | head -n 1)
          yes | $SDK_PATH --sdk_root=$ANDROID_HOME --licenses
          
          buildozer -v android debug
        env:
          BUILDOZER_WARN_ON_ROOT: 0
